# Generated by Django 3.1.3 on 2021-03-03 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
        migrations.AlterModelOptions(
            name='snippet',
            options={'verbose_name': 'Snippet', 'verbose_name_plural': 'Snippets'},
        ),
    ]
