# Generated by Django 3.1.3 on 2021-03-03 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20210303_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='update',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='create',
            new_name='update_date',
        ),
    ]
