# Generated by Django 3.1.3 on 2021-03-04 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20210303_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='languague',
            new_name='language',
        ),
    ]
