# Generated by Django 3.1.3 on 2021-03-05 18:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_auto_20210303_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='snippet',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
