# Generated by Django 3.1.3 on 2021-03-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_auto_20210305_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='snippet',
            field=models.TextField(),
        ),
    ]
